apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: pf9-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
{{- if .DockerRegistry }}
      - image: {{ .DockerRegistry }}/nginx:stable
{{- else }}
      - image: nginx:stable
{{- end }}
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-conf
          readOnly: true
        - mountPath: /var/log/nginx
          name: log
{{- if .DockerRegistry }}          
      - image: {{ .DockerRegistry }}/grafana/grafana:7.2.0
{{- else }}
      - image: grafana/grafana:7.2.0
{{- end }}
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/grafana
          name: grafana-conf
          readOnly: true
        - mountPath: /var/lib/grafana
          name: grafana-storage
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
        - mountPath: /grafana-dashboard-definitions/0/grafana-dashboard-apiserver
          name: grafana-dashboard-apiserver
        - mountPath: /usr/share/grafana/public/dashboards/home.json
          name: grafana-dashboard-cluster-explorer
          subPath: home.json
        - mountPath: /grafana-dashboard-definitions/1/grafana-dashboard-events
          name: grafana-dashboard-events
        - mountPath: /grafana-dashboard-definitions/2/grafana-dashboard-fs
          name: grafana-dashboard-fs
        - mountPath: /grafana-dashboard-definitions/3/grafana-dashboard-kubelet
          name: grafana-dashboard-kubelet
        - mountPath: /grafana-dashboard-definitions/4/grafana-dashboard-kubernetes
          name: grafana-dashboard-kubernetes
        - mountPath: /grafana-dashboard-definitions/5/grafana-dashboard-memusage
          name: grafana-dashboard-memusage
        - mountPath: /grafana-dashboard-definitions/6/grafana-dashboard-network
          name: grafana-dashboard-network
        - mountPath: /grafana-dashboard-definitions/7/grafana-dashboard-node-exporter
          name: grafana-dashboard-node-exporter
        - mountPath: /grafana-dashboard-definitions/8/grafana-dashboard-pvc
          name: grafana-dashboard-pvc
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - emptyDir: {}
        name: log
      - name: grafana-datasources
        secret:
          defaultMode: 420
          secretName: grafana-datasources
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          name: nginx-conf
        name: nginx-conf
      - configMap:
          defaultMode: 420
          items:
          - key: grafana.ini
            path: grafana.ini
          name: grafana-conf
        name: grafana-conf
      - configMap:
          defaultMode: 420
          name: grafana-dashboards
        name: grafana-dashboards
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-apiserver
        name: grafana-dashboard-apiserver
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-cluster-explorer
        name: grafana-dashboard-cluster-explorer
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-events
        name: grafana-dashboard-events
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-fs
        name: grafana-dashboard-fs
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-kubelet
        name: grafana-dashboard-kubelet
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-kubernetes
        name: grafana-dashboard-kubernetes
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-memusage
        name: grafana-dashboard-memusage
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-network
        name: grafana-dashboard-network
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-node-exporter
        name: grafana-dashboard-node-exporter
      - configMap:
          defaultMode: 420
          name: grafana-dashboard-pvc
        name: grafana-dashboard-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui
  namespace: pf9-monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: grafana
