---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "pf9:prometheus-monhelper"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - podmonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  - events
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ''
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-monhelper
  namespace: pf9-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pf9:prometheus-monhelper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  "pf9:prometheus-monhelper"
subjects:
- kind: ServiceAccount
  name: prometheus-monhelper
  namespace: pf9-operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monhelper
  namespace: pf9-operators
spec:
  selector:
    matchLabels:
      app: mon-helper
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        app: mon-helper
        k8s-app: prometheus-operator
    spec:
      serviceAccount: prometheus-monhelper
      containers:
      - args:
        - --mode=k8s
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
{{- if .DockerRegistry }}
        image: {{ .DockerRegistry }}/platform9/monhelper:v2.0.0
{{- else }}
        image: platform9/monhelper:v2.0.0        
{{- end }}
        imagePullPolicy: IfNotPresent
        name: monhelper
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 25Mi
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mon-helper
  name: mon-svc
  namespace: pf9-operators
spec:
  clusterIP: None
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app: mon-helper
