apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: baremetal-operator-selfsigned-issuer
  namespace: baremetal-operator-system
spec:
  selfSigned: {}
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baremetal-operator-serving-cert
  namespace: baremetal-operator-system
spec:
  dnsNames:
  - baremetal-operator-webhook-service.baremetal-operator-system.svc
  - baremetal-operator-webhook-service.baremetal-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: baremetal-operator-selfsigned-issuer
  secretName: bmo-webhook-server-cert
