apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator-ironic
  namespace: baremetal-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: baremetal-operator-ironic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: baremetal-operator-ironic
    spec:
      containers:
      - command:
        - /bin/runironic-api
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-secret
        envFrom:
        - configMapRef:
            name: ironic-htpasswd-configmap
        - configMapRef:
            name: ironic-bmo-configmap
        image: platform9/ironic-image:latest
        imagePullPolicy: Always
        name: ironic-api
        volumeMounts:
        - mountPath: /auth/ironic-rpc
          name: ironic-rpc-auth-config
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic-conductor
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-secret
        envFrom:
        - configMapRef:
            name: ironic-htpasswd-configmap
        - configMapRef:
            name: ironic-bmo-configmap
        image: platform9/ironic-image:latest
        imagePullPolicy: Always
        name: ironic-conductor
        volumeMounts:
        - mountPath: /auth/ironic-inspector
          name: ironic-inspector-auth-config
          readOnly: true
        - mountPath: /auth/ironic-rpc
          name: ironic-rpc-auth-config
          readOnly: true
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runironic-inspector
        envFrom:
        - configMapRef:
            name: ironic-inspector-htpasswd-configmap
        - configMapRef:
            name: ironic-bmo-configmap
        image: platform9/ironic-image:latest
        imagePullPolicy: Always
        name: ironic-inspector
        volumeMounts:
        - mountPath: /auth/ironic
          name: ironic-auth-config
          readOnly: true
      - command:
        - /bin/rundnsmasq
        envFrom:
        - configMapRef:
            name: ironic-bmo-configmap
        image: platform9/ironic-image:latest
        imagePullPolicy: Always
        name: ironic-dnsmasq
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runmariadb
        env:
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mariadb-password-secret
        - name: RESTART_CONTAINER_CERTIFICATE_UPDATED
          valueFrom:
            configMapKeyRef:
              key: RESTART_CONTAINER_CERTIFICATE_UPDATED
              name: ironic-bmo-configmap
        image: platform9/ironic-image:latest
        imagePullPolicy: Always
        name: mariadb
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      - command:
        - /bin/runlogwatch.sh
        image: platform9/ironic-image:latest
        imagePullPolicy: Always
        name: ironic-log-watch
        volumeMounts:
        - mountPath: /shared
          name: ironic-data-volume
      hostNetwork: true
      volumes:
      - name: ironic-auth-config
        secret:
          secretName: ironic-auth-config-secret
      - name: ironic-inspector-auth-config
        secret:
          secretName: ironic-inspector-auth-config-secret
      - name: ironic-rpc-auth-config
        secret:
          secretName: ironic-rpc-auth-config-secret
      - emptyDir: {}
        name: ironic-data-volume
