apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
{{- if .base64EncMetallbConfig }}
{{ .base64EncMetallbConfig | indent 4 }}
{{- else }}  
    address-pools:
    - name: default
      protocol: layer2
      addresses:
{{ .MetallbIpRange }}
{{- end }}